const {test}=require('node:test'),assert=require('node:assert/strict');
const {batchedReport,plan}=require('../src/report-batches.cjs');
function evidence(count=18){return {source:{duration_seconds:300},shots:Array.from({length:count},(_,i)=>({evidence_id:'shot-'+(i+1),start_seconds:i*.5,end_seconds:(i+1)*.5,visuals:'测试画面'})),transcript:[],scenes:[],audio:[],uncertainties:[]};}
function report(part,long=false){return {title:'报告',overview:'测试概览',sections:[{title:'视觉',body:'测试画面'}],segments:part.shots.map(s=>({title:s.evidence_id,evidence_ids:[s.evidence_id],analysis:long?'画面'.repeat(500):'画面证据',video_generation_prompt:'测试提示词'})),uncertainties:'无'};}
function result(value,finish='stop'){return {choices:[{finish_reason:finish,message:{content:JSON.stringify(value)}}]};}
function checkpoint(){let saved;return {read:async()=>structuredClone(saved),write:async value=>{saved=structuredClone(value);},get value(){return saved;}};}
function respond(body,long=false){const input=JSON.parse(body.messages[1].content);return input.shots?result(report(input,long)):result({title:'完整概览',overview:'全片总结',sections:[],uncertainties:'无'});}
test('120-shot report exceeds old single-response size, all references and ordering survive batching',async()=>{let calls=0;const cp=checkpoint(),data=evidence(120);const generated=await batchedReport(data,{model:'test'},async(_,body)=>{calls++;assert.ok(JSON.parse(body.messages[1].content).shots?.length<=6||JSON.parse(body.messages[1].content).batches);return respond(body,true);},{checkpoint:cp});assert.equal(calls,21);assert.equal(generated.report.segments.length,120);assert.ok(JSON.stringify(generated.report).length>100000);assert.deepEqual(generated.report.segments.flatMap(s=>s.evidence_ids),data.shots.map(s=>s.evidence_id));assert.equal(generated.report.segments[119].id,'seg-120');});
test('network failure persists completed work; restart calls only remaining batches and overview',async()=>{const cp=checkpoint();let count=0;await assert.rejects(batchedReport(evidence(),{model:'test'},async(_,body)=>{count++;if(count===2)throw Error('503');return respond(body);},{checkpoint:cp}),/503/);assert.equal(count,2);assert.equal(Object.keys(cp.value.completed).length,1);const requested=[];await batchedReport(evidence(),{model:'test'},async(_,body)=>{requested.push(JSON.parse(body.messages[1].content));return respond(body);},{checkpoint:cp});assert.equal(requested.length,3);assert.equal(requested[0].shots[0].evidence_id,'shot-7');let extra=0;await batchedReport(evidence(),{model:'test'},async()=>{extra++;},{checkpoint:cp});assert.equal(extra,0);});
test('confirmed output truncation subdivides and persists the new plan; no same-sized retry',async()=>{const cp=checkpoint(),sizes=[];const value=await batchedReport(evidence(6),{model:'test'},async(_,body)=>{const part=JSON.parse(body.messages[1].content);if(!part.shots)return respond(body);sizes.push(part.shots.length);return part.shots.length>2?result({},'length'):result(report(part));},{checkpoint:cp});assert.equal(value.report.segments.length,6);assert.deepEqual(sizes,[6,3,2,1,3,2,1]);assert.deepEqual(cp.value.plan.map(ids=>ids.length),[2,1,2,1]);});
test('cancel between batches preserves finished work and changes of model/evidence invalidate cache',async()=>{const cp=checkpoint(),controller=new AbortController();let calls=0;await assert.rejects(batchedReport(evidence(12),{model:'a'},async(_,body)=>{calls++;return respond(body);},{checkpoint:cp,signal:controller.signal,stage:text=>{if(text.includes('批已保存'))controller.abort();}}),{name:'AbortError'});assert.equal(calls,1);assert.equal(Object.keys(cp.value.completed).length,1);calls=0;await batchedReport(evidence(12),{model:'b'},async(_,body)=>{calls++;return respond(body);},{checkpoint:cp});assert.equal(calls,3);const changed=evidence(12);changed.shots[0].visuals='变更证据';calls=0;await batchedReport(changed,{model:'b'},async(_,body)=>{calls++;return respond(body);},{checkpoint:cp});assert.equal(calls,3);});
test('overview truncation preserves every completed batch; resume requests overview only',async()=>{const cp=checkpoint();await assert.rejects(batchedReport(evidence(12),{model:'test'},async(_,body)=>JSON.parse(body.messages[1].content).shots?respond(body):result({},'length'),{checkpoint:cp}),/下次只继续概览/);assert.equal(Object.keys(cp.value.completed).length,2);let count=0;await batchedReport(evidence(12),{model:'test'},async(_,body)=>{count++;assert.ok(JSON.parse(body.messages[1].content).batches);return respond(body);},{checkpoint:cp});assert.equal(count,1);});
test('single-shot overflow stops finitely and invalid JSON is not retried',async()=>{let calls=0;await assert.rejects(batchedReport(evidence(1),{model:'test'},async()=>{calls++;return result({},'length');}),/单个镜头/);assert.equal(calls,1);calls=0;await assert.rejects(batchedReport(evidence(12),{model:'test'},async()=>{calls++;return result({});}),/报告结构/);assert.equal(calls,1);});
test('oversized input splits without dropping original evidence',()=>{const data=evidence(6);data.shots.forEach(s=>s.visuals='x'.repeat(30000));const groups=plan(data);assert.ok(groups.length>1);assert.deepEqual(groups.flat(),data.shots.map(s=>s.evidence_id));});
